// Aspire AppHost — the dev-time orchestrator. One `dotnet run` (or F5) brings up the whole
// platform: the Web API plus the three off-path hosts, each wired with the inherited service
// defaults (OTel, health, resilience) and surfaced in the Aspire dashboard with live traces,
// logs, and metrics. This project is dev/deploy-time only — it never ships inside a service.
//
// Run it:  dotnet run --project src/ApiPlatform.AppHost
// then open the dashboard URL it prints (OTEL_EXPORTER_OTLP_ENDPOINT is injected for you).

var builder = DistributedApplication.CreateBuilder(args);

// The Projects.* types are source-generated by the Aspire SDK from the ProjectReferences.
var api = builder.AddProject<Projects.ApiPlatform_Api>("api")
    .WithEnvironment("AUTH_MODE", "LocalJwt");

builder.AddProject<Projects.ApiPlatform_Poller>("poller");
builder.AddProject<Projects.ApiPlatform_EventSource>("eventsource");
builder.AddProject<Projects.ApiPlatform_Mcp>("mcp");

// `api` is captured so dependents (e.g. an MCP host calling the API, or a future gateway)
// can `.WithReference(api)` to get service discovery + the resolved base address for free.
_ = api;

builder.Build().Run();
